
services:
  app:
    build: . 
    image: node:14
    container_name: bestpick_api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql         
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=ReviewAPP
    volumes:
      - .:/app
    working_dir: /app
    command: "sh -c 'node server.js && python3 botgetprice.py'"
    depends_on:
      - mysql
    networks:
      - mynetwork

  nginx:
    image: nginx
    container_name: mynginx
    ports:
      - "8080:80"
    networks:
      - mynetwork

  mysql:
    image: mysql
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ReviewAPP
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
